previews:
  generation: automatic

services:

  - type: web
    runtime: docker
    name: upcycling_project
    plan: free 
    region: oregon
    buildCommand: docker build -t upcycling_project .
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        sync: false      
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      fromService: db
    autoDeploy: false

databases:

  - type: database
    name: postgres
    databaseType: postgres
    plan: free 
    region: oregon
    ipAllowList: 
      - source: 0.0.0.0/0
        description: everywhere
    databaseName: upcyworld
    user: root
    envVars:
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
     